# Tasks

## Task 1: Source the Data Set

Import the `sklearn.datasets` module.

In [28]:
# Import scikit-learn module
import sklearn as skl # sklearn is used for machine learning tasks like load data sets, split the data, testing, etc.

### Load Iris data set
The `sklearn.datasets.load_iris` function ([see official documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html)) Load and return the iris dataset.

In [29]:
# Loading the Iris dataset
from sklearn.datasets import load_iris 

# Creating data variable and putting the iris dataset into it
# https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html
data = skl.datasets.load_iris() # Load the iris dataset into the data variable

### Explain, in your own words, what the load_iris() function returns.

The `load_iris()` is a function which returns a collection of information about flowers. This data has a description of measurements, labels, names and some details about flowers. The function organizes this information in a dictinary-like structure which gives us an opportunity to access and use for analysis or machine learning tasks.

## Task 2: Explore the Data Structure

Print and explain the shape of the data set, the first and last 5 rows of the data, the feature names, and the target classes.

In [30]:
# https://numpy.org/doc/2.1/reference/generated/numpy.shape.html

print(data['data'].shape) #shape is a numpy array key, which shows us dimension of the data, how many rows and columns

(150, 4)


In [31]:
# to show first 5 rows of the data we can use slicing
print(data['data'][:5]) # Print the first 5 rows of the data

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [32]:
# to show last 5 rows of the data we can use also slicing
print(data['data'][-5:]) # Print the last 5 rows of the data

[[6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


In [33]:
print(data['feature_names']) # Print the feature names of the data, which are the names of the columns in the data

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [34]:
print(data['target_names']) # Print the target variable, which is the species of the iris flower, which is the name of the rows in the data

['setosa' 'versicolor' 'virginica']


## Task 3: Summarize the Data

For each feature in the dataset, calculate and display:  

- [mean](#mean)
- [minimum](#minimum)
- [maximum](#maximum)
- [standard_deviation](#standard_deviation)
- [median](#median)

In [35]:
# https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-import-numpy
import numpy as np # Importing numpy package, which used to operate efficiently on these data structures.

Finding out how many columns do we need to calculate

In [36]:
# Getting list with four feature names
feature_names = data['feature_names']
print(feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


The Indexing, slicing and iterating documentation ([see official documentation](https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating)) help us to get an acces for any column we need.

In [37]:
# https://numpy.org/devdocs/user/quickstart.html#indexing-slicing-and-iterating
# We can also access the features names by using the index of the list
first_feature = data['data'][:,0] # (:) means we take all rows, 0 - first column
second_feature = data['data'][:,1] # (:) means we take all rows, 1 - second column
third_feature = data['data'][:,2] # (:) means we take all rows, 2 - first column
fourth_feature = data['data'][:,3] # (:) means we take all rows, 3 - first column

## Mean

Calculating and display mean for each feature `numpy.mean` function ([see official documentation](https://numpy.org/doc/2.2/reference/generated/numpy.mean.html#numpy-mean)) Returns the average of the array elements.

In [52]:
# https://numpy.org/doc/2.2/reference/generated/numpy.mean.html#numpy-mean
print(f"The average of the {data['feature_names'][0]} is: {np.mean(first_feature)}") # Print the average of the first feature
print(f"The average of the {data['feature_names'][1]} is: {np.mean(second_feature)}") # Print the average of the second feature
print(f"The average of the {data['feature_names'][2]} is: {np.mean(third_feature)}") # Print the average of the third feature
print(f"The average of the {data['feature_names'][3]} is: {np.mean(fourth_feature)}") # Print the average of the fourth feature

The average of the sepal length (cm) is: 5.843333333333334
The average of the sepal width (cm) is: 3.0573333333333337
The average of the petal length (cm) is: 3.7580000000000005
The average of the petal width (cm) is: 1.1993333333333336


## Minimum

In [54]:
#  https://numpy.org/doc/2.2/reference/generated/numpy.min.html#numpy-min
print(f"The minimum of the {data['feature_names'][0]} is: {np.min(first_feature)}") # Print the minimum of the array
print(f"The minimum of the {data['feature_names'][1]} is: {np.min(second_feature)}") # Print the minimum of the array
print(f"The minimum of the {data['feature_names'][2]} is: {np.min(third_feature)}") # Print the minimum of the array
print(f"The minimum of the {data['feature_names'][3]} is: {np.min(fourth_feature)}") # Print the minimum of the array

The minimum of the sepal length (cm) is: 4.3
The minimum of the sepal width (cm) is: 2.0
The minimum of the petal length (cm) is: 1.0
The minimum of the petal width (cm) is: 0.1


## Maximum

In [ ]:
#  https://numpy.org/doc/2.2/reference/generated/numpy.max.html#numpy-max
print(f"The maximum of the {data['feature_names'][0]} is: {np.max(first_feature)}") # Print the maximum of the first feature
print(f"The maximum of the {data['feature_names'][1]} is: {np.max(second_feature)}") # Print the maximum of the second feature
print(f"The maximum of the {data['feature_names'][2]} is: {np.max(third_feature)}") # Print the maximum of the third feature
print(f"The maximum of the {data['feature_names'][3]} is: {np.max(fourth_feature)}") # Print the maximum of the fourth feature

The maximum of the sepal length (cm) is: 7.9
The maximum of the sepal width (cm) is: 4.4
The maximum of the petal length (cm) is: 6.9
The maximum of the petal width (cm) is: 2.5


## Standard_deviation

In [ ]:
#  https://numpy.org/doc/2.2/reference/generated/numpy.std.html#numpy-std
print(f"The standard deviation of the {data['feature_names'][0]} is: {np.std(first_feature)}") # Print the standard deviation of the first feature
print(f"The standard deviation of the {data['feature_names'][1]} is: {np.std(second_feature)}") # Print the standard deviation of the second feature
print(f"The standard deviation of the {data['feature_names'][2]} is: {np.std(third_feature)}") # Print the standard deviation of the third feature
print(f"The standard deviation of the {data['feature_names'][3]} is: {np.std(fourth_feature)}") # Print the standard deviation of the fourth feature

The standard deviation of the sepal length (cm) is: 0.8253012917851409
The standard deviation of the sepal width (cm) is: 0.4344109677354946
The standard deviation of the petal length (cm) is: 1.759404065775303
The standard deviation of the petal width (cm) is: 0.7596926279021594


## Median

In [57]:
#  https://numpy.org/doc/2.1/reference/generated/numpy.median.html#numpy-median
print(f"The median of the {data['feature_names'][0]} is: {np.median(first_feature)}") # Print the median of the first feature  
print(f"The median of the {data['feature_names'][1]} is: {np.median(second_feature)}") # Print the median of the second feature
print(f"The median of the {data['feature_names'][2]} is: {np.median(third_feature)}") # Print the median of the third feature
print(f"The median of the {data['feature_names'][3]} is: {np.median(fourth_feature)}") # Print the median of the fourth feature

The median of the sepal length (cm) is: 5.8
The median of the sepal width (cm) is: 3.0
The median of the petal length (cm) is: 4.35
The median of the petal width (cm) is: 1.3
